#TODO NOTE use aswdock Dockerfile
name: ci

on:
  push:
    branches: master

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build -t test-image .
      
      - name: Tags Image
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker tag test-image ${USERNAME}/test-image:latest
          docker tag test-image ${USERNAME}/test-image:${{ github.sha }} 
      - name: Push 
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
         docker push ${USERNAME}/test-image:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: gitaction-test
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t gitaction-test .
          docker tag ${ECR_REPOSITORY}:${IMAGE_TAG} 370599928061.dkr.ecr.us-east-2.amazonaws.com/${ECR_REPOSITORY:${IMAGE_TAG}
          docker push 370599928061.dkr.ecr.us-east-2.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo $IMAGE_TAG


