name: Docker publish
  #description: load source and Dockerfile to create an image and publish it on docker-hub

on: 
  push:
    branches: master

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest  
    steps: 
      - name: test text
        run: printf "Hello World"

