name: Test Workflow

on: push

jobs:
  build:
    name: Hello Text
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world!" 
        #env:
        #  FIRST_NAME: Mona
        #  middle_name: The
        #  Last_Name: Octocat 
